---
cachy_container_base_path: /opt/containers
linuxserver_timezone: Etc/UTC
distrobox_user: "{{ ansible_user }}"
distrobox_home_dir: "{{ ansible_user_dir | default('/home/' ~ ansible_user) }}/.distrobox/home"
dotfiles_work_tree: "{{ distrobox_home_dir }}"
dotfiles_git_dir: "{{ dotfiles_work_tree }}/.dotfiles.git"
snapper_subvolumes: []
# snapper_subvolumes:
#   - name: home
#     path: /home
dotfiles_repo_version: "HEAD"
